"""empty message

Revision ID: 630e49c70083
Revises: fb7450de6abf
Create Date: 2024-09-14 09:34:07.195712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630e49c70083'
down_revision = 'fb7450de6abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reservation_date', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'service', ['service_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reservation_date')
        batch_op.drop_column('service_id')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
