"""empty message

Revision ID: ce431f563cda
Revises: a5cffa318ac2
Create Date: 2024-09-11 18:17:02.698767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce431f563cda'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('familiar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('parentesco', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('upload_date', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('is_client', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sexo', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('altura', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nombre', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('peso', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('edad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_de_nacimiento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('alergias_alimentarias', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('medicamentos_actuales', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vacunas', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('historial_familiar', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('numero_salud', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ciudad', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('available_times', sa.JSON(), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('available_times')
        batch_op.drop_column('ciudad')
        batch_op.drop_column('image_url')
        batch_op.drop_column('numero_salud')
        batch_op.drop_column('historial_familiar')
        batch_op.drop_column('vacunas')
        batch_op.drop_column('medicamentos_actuales')
        batch_op.drop_column('alergias_alimentarias')
        batch_op.drop_column('fecha_de_nacimiento')
        batch_op.drop_column('edad')
        batch_op.drop_column('peso')
        batch_op.drop_column('nombre')
        batch_op.drop_column('altura')
        batch_op.drop_column('sexo')
        batch_op.drop_column('is_client')
        batch_op.drop_column('username')

    op.drop_table('user_image')
    op.drop_table('service')
    op.drop_table('saved_service')
    op.drop_table('reservation')
    op.drop_table('familiar')
    op.drop_table('comment')
    # ### end Alembic commands ###
